apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo-express-deployment
  labels:
    app: {{ .Release.Name }}-mongo-express-deployment
spec:
  replicas: {{ .Values.replicaCountApp }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo-express-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo-express-deployment
    spec:
      containers:
      - name: {{ .Release.Name }}-mongo-express-deployment
        image: {{.Values.image.app}}
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: db-url
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}mongo-express-service
spec:
  selector:
    app: {{ .Release.Name }}-mongo-express-deployment
  type:  {{ .Values.appService.type }}
  ports:
  -  port:  8081
     targetPort:  8081
     nodePort: {{ .Values.appService.port }}